// Authentication States
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL';
export const SEND_DATA_SUCCESS = 'SEND_DATA_SUCCESS';
export const SEND_DATA_FAIL = 'SEND_DATA_FAIL';

export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS';
export const GET_FEATURES_FAIL = 'GET_FEATURES_FAIL';

export const GET_FEATURES_COUNT_SUCCESS = 'GET_FEATURES_COUNT_SUCCESS';
export const GET_FEATURES_COUNT_FAIL = 'GET_FEATURES_COUNT_FAIL';

export const GET_DECEPTIVE_COUNT_SUCCESS = 'GET_DECEPTIVE_COUNT_SUCCESS';
export const GET_DECEPTIVE_COUNT_FAIL = 'GET_DECEPTIVE_COUNT_FAIL';

export const GET_ACTUAL_FEATURES_SUCCESS = 'GET_ACTUAL_FEATURES_SUCCESS';
export const GET_ACTUAL_FEATURES_FAIL = 'GET_ACTUAL_FEATURES_FAIL';

export const GET_T_SENTIMENT_COUNT_SUCCESS = 'GET_T_SENTIMENT_COUNT_SUCCESS';
export const GET_T_SENTIMENT_COUNT_FAIL = 'GET_T_SENTIMENT_COUNT_FAIL';

export const GET_T_DECEPTIVE_COUNT_SUCCESS = 'GET_T_DECEPTIVE_COUNT_SUCCESS';
export const GET_T_DECEPTIVE_COUNT_FAIL = 'GET_T_DECEPTIVE_COUNT_FAIL';

export const GET_NBD_ACCURACY_SUCCESS = 'GET_NBD_ACCURACY_SUCCESS';
export const GET_NBD_ACCURACY_FAIL = 'GET_NBD_ACCURACY_FAIL';

export const GET_RFD_ACCURACY_SUCCESS = 'GET_RFD_ACCURACY_SUCCESS';
export const GET_RFD_ACCURACY_FAIL = 'GET_RFD_ACCURACY_FAIL';

export const GET_SVMD_ACCURACY_SUCCESS = 'GET_SVMD_ACCURACY_SUCCESS';
export const GET_SVMD_ACCURACY_FAIL = 'GET_SVMD_ACCURACY_FAIL';

export const GET_DECEPTIVE_ACCURACIES_SUCCESS = 'GET_DECEPTIVE_ACCURACIES_SUCCESS';
export const GET_DECEPTIVE_ACCURACIES_FAIL = 'GET_DECEPTIVE_ACCURACIES_FAIL';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_DATA_COUNTS_SUCCESS = 'GET_DATA_COUNTS_SUCCESS';
export const GET_DATA_COUNTS_FAIL = 'GET_DATA_COUNTS_FAIL';